// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eojqpvcjpsjxomecubyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvanFwdmNqcHNqeG9tZWN1Ynl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MzMwODEsImV4cCI6MjA2MTMwOTA4MX0.tl6RoGrSTXaMkLxvSOWolw075nRJQpytYOiE1Hf-930";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);